apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linea.maru.fullname" . }}
  labels:
    {{- include "linea.labels" (dict "context" . "component" .Values.maru.name "name" .Values.maru.name) | nindent 4 }}
type: Opaque
stringData:
  key: {{ .Values.maru.secret.key | quote }}
