apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linea.ethstats.fullname" . }}
  labels:
    {{- include "linea.labels" (dict "context" . "component" .Values.ethstats.name "name" .Values.ethstats.name) | nindent 4 }}
type: Opaque
stringData:
  ws_secret: {{ .Values.secret.ws_secret | quote }}
