apiVersion: v1
kind: Service
metadata:
  name: {{ include "linea.ethstats.fullname" . }}
  labels:
    {{- include "linea.labels" (dict "context" . "component" .Values.ethstats.name "name" .Values.ethstats.name) | nindent 4 }}
spec:
  type: {{ .Values.ethstats.service.type }}
  ports:
    - port: {{ .Values.ethstats.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "linea.selectorLabels" (dict "context" . "name" .Values.ethstats.name) | nindent 4 }}
