apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linea.besu.fullname" . }}
  labels:
    {{- include "linea.labels" (dict "context" . "component" .Values.besu.name "name" .Values.besu.name) | nindent 4 }}
type: Opaque
stringData:
  ethstats: "ws://besu-node:{{ .Values.secret.ws_secret }}@{{ include "linea.ethstats.addr" . }}"
