---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: linea
spec:
  gatewayClassName: linea
  listeners:
  - name: besu
    hostname: besu-node.mazzarino.cz
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
  - name: ethstats
    hostname: ethstats.mazzarino.cz
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
