{{- if .Values.sender.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linea.sender.fullname" . }}
  labels:
    {{- include "linea.labels" (dict "context" . "component" .Values.sender.name "name" .Values.sender.name) | nindent 4 }}
type: Opaque
stringData:
  private_key: {{ .Values.sender.secret.private_key | quote }}
{{- end }}