{{- if .Values.sender.enabled -}}
{{- if .Values.sender.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "linea.sender.serviceAccountName" . }}
  labels:
    {{- include "linea.labels" (dict "context" . "component" .Values.sender.name "name" .Values.sender.name) | nindent 4 }}
  {{- with .Values.sender.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.sender.serviceAccount.automount }}
{{- end }}
{{- end }}