apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linea.sequencer.fullname" . }}
  labels:
    {{- include "linea.labels" (dict "context" . "component" .Values.sequencer.name "name" .Values.sequencer.name) | nindent 4 }}
type: Opaque
stringData:
  ethstats: "ws://sequencer-node:{{ .Values.secret.ws_secret }}@{{ include "linea.ethstats.addr" . }}"
  key: "{{ .Values.sequencer.secret.key }}"
